version: '3.9'
services:
  openldap:
    image: bitnami/openldap:2
    container_name: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=password
    volumes:
      - 'openldap_data:/bitnami/openldap'
# Uncomment below to use from GitHub Repo
      - './example.ldif:/ldifs/example-quickstart.ldif'
#      - './resources/ldap/example.ldif:/ldifs/example.ldif'
  ldap-commander:
    image: balemy/ldap-commander:latest
    container_name: ldap-commander
    environment:
      LDAPCOM_CONN1_DSN: "ldap://openldap:1389"
      LDAPCOM_CONN1_BASE_DN: "dc=example,dc=org"
      LDAPCOM_CONN1_ADMIN_DN: "cn=admin,dc=example,dc=org"
      LDAPCOM_CONN1_ADMIN_PASSWORD: "password"
    ports:
      - "8080:8080"
    depends_on:
      - openldap
volumes:
  openldap_data:
    driver: local
