version: '3.9'
services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=true
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,bitnami-openldap-memberof
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - './ldap-example-data.ldif:/ldifs/example.ldif'
      - './ldap-memberof.ldif:/opt/bitnami/openldap/etc/schema/bitnami-openldap-memberof.ldif'
  ldap-commander:
    image: balemy/ldap-commander:latest
    container_name: ldap-commander
    environment:
      - ENABLE_CADDY=false
      - HOSTNAME=ldap.example.com
    ports:
      - "8080:8080"
#      - "80:80"
#      - "443:443"
    depends_on:
      - openldap
    volumes:
      - './config.php:/app/config/ldap.php'
      - ./data/caddy:/data
volumes:
  openldap_data:
    driver: local
