<?php

namespace Balemy\LdapCommander\Modules\GroupManager;

use Balemy\LdapCommander\LDAP\LdapFormModel;

class GroupForm extends LdapFormModel
{
    protected array $requiredObjectClasses = ['groupOfUniqueNames'];

    public function load(array $data): bool
    {
        if (empty($data[$this->getFormName()]['uniqueMember'])) {
            $data[$this->getFormName()]['uniqueMember'] = [];
        }

        return parent::load($data); // TODO: Change the autogenerated stub
    }

    public function getFormName(): string
    {
        return 'GroupForm';
    }

}
