on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.env.example'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  schedule:
    - cron: '0 0 * * *'

name: build

jobs:
  codeception-tests:

    name: Codeception Tests

    env:
      extensions: fileinfo, ldap, intl, pdo_sqlite

    runs-on: ubuntu-latest

    services:
      ldap:
        image: bitnami/openldap
        ports:
          - 1389:1389
        env:
          LDAP_CONFIG_ADMIN_ENABLED: true
          LDAP_ADMIN_USERNAME: admin
          LDAP_ADMIN_PASSWORD: secret
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          tools: composer:v2

      - name: Start Selenium
        run: |
          docker run --detach --net=host --shm-size="2g" selenium/standalone-chrome

      - name: Update composer
        run: composer self-update

      - name: Install dependencies with composer
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests with codeception
        run: |
          php -S 127.0.0.1:8080 -t public > ./runtime/yii.log 2>&1 &
          vendor/bin/codecept run
